# Site settings
title: Mundo do Wumpus - Intelegência Computacional
description: "Ambiente para estudo de modelos de Apredizagem de Máquina da disciplina de Inteligência Computacional."

# Build settings
theme: minimal
